chore: Replacing MenuList with VirtualMenuList
weka/weka-ui-components pull request #218
Opened 2024-12-23 13:26 UTC by udia76

2025-01-05 15:09 UTC, udia76 commented on lib/components/inputs/Select/SelectOption/SelectOption.tsx
Thanks for your comments @sofa-tata , I've added some extra 5px for the list to avoid redundant scroll, also, added some special case for subLabel, I hope that now it covers all the common cases. Please check again.

2025-01-06 15:48 UTC, sofa-tata commented on lib/components/inputs/Select/VirtualMenuList/VirtualMenuList.tsx
there are still 2 missing rounded corners (now top right and top left): 
plus, as I can see, there used to be a small padding above the first option in the list and I guess below the last one
![Screenshot 2025-01-06 at 17 41 37](https://github.com/user-attachments/assets/dd8560a5-a59f-4130-b78c-7cca9422b48a)

2025-01-06 15:48 UTC, sofa-tata commented on lib/components/inputs/Select/SelectOption/SelectOption.tsx
This thing looks good now, just a small note: there shouldn't be a border between the options (+ padding and corners):

was:
![Screenshot 2025-01-06 at 17 47 19](https://github.com/user-attachments/assets/489efb93-fd7b-4cd7-b382-e227d124333d)

is:
![Screenshot 2025-01-06 at 17 45 38](https://github.com/user-attachments/assets/0b3b6abc-1542-4fe3-9ffe-b919108455c5)

2025-01-07 09:26 UTC, tellmywife requested changes

2025-01-07 09:26 UTC, tellmywife commented on lib/components/inputs/Select/SelectOption/selectOption.scss
> +      .main-label {
Since styles are the same, we can list classes together:
```suggestion
      .main-label,
      .sub-label
       {
       ...
       }
```

2025-01-09 15:41 UTC, mvoloshin0458 commented on package.json
> +    "react-window": "^1.8.11",
let's use `@tanstack/react-virtual` which is in the repo

2025-01-09 15:45 UTC, mvoloshin0458 requested changes

2025-01-09 15:45 UTC, mvoloshin0458 commented on package.json
> +    "react-window": "^1.8.11",
let's use @tanstack/react-virtual which is in the repo

2025-01-10 07:28 UTC, tellmywife approved these changes

2025-01-12 07:38 UTC, sofa-tata approved these changes

2025-01-12 11:17 UTC, udia76 commented on package.json
> +    "react-window": "^1.8.11",
ok, I've changed the solution to work with `react-virtual `as you suggested. I've noticed that we had some beta version of r`eact-virtual`, so I've upgraded it to the latest also.

2025-01-12 13:59 UTC, mvoloshin0458 approved these changes

2025-01-12 14:19 UTC, merged