topology page
weka/weka-ui-components pull request #23
Opened 2023-04-19 15:08 UTC by mvoloshin0458

2023-04-24 16:43 UTC, mvoloshin0458 commented on src/utils.tsx
> +
I'll need to discuss it

2023-04-25 08:49 UTC, mvoloshin0458 commented on src/utils.tsx
> +        .localeCompare(objB.toString().toLowerCase())
remove

2023-04-25 08:50 UTC, mvoloshin0458 commented on src/utils.tsx
> +
remove

2023-04-27 14:24 UTC, sofa-tata requested changes

2023-04-27 14:24 UTC, sofa-tata commented on src/components/Table/table.scss
> +  }
can remove

2023-04-27 14:24 UTC, sofa-tata commented on src/components/Table/Table.tsx
> +          <Loader />
can remove the div

2023-05-03 11:14 UTC, mvoloshin0458 commented
@sofa-tata tested in wekapp and gohome

2023-05-04 08:52 UTC, sofa-tata approved these changes

2023-05-04 10:03 UTC, merged